from pathlib import Path
p=Path('index.html'); bp=Path('functions/index.js'); h=p.read_text(); b=bp.read_text()

# Insert account modal before auth modal.
marker='''    <!-- Auth Modal -->\n'''
if 'id="accountModal"' not in h:
    modal='''    <!-- Customer Account Modal -->\n    <div class="auth-modal" id="accountModal" role="dialog" aria-modal="true" aria-labelledby="accountModalTitle" aria-hidden="true">\n        <div class="auth-modal-content" style="max-width:760px;">\n            <button type="button" class="close-modal" onclick="closeAccountModal()" aria-label="Close account">×</button>\n            <h2 id="accountModalTitle" style="font-family:'Bebas Neue',sans-serif;font-size:2.5rem;margin-bottom:1rem;letter-spacing:.08em;">My Account</h2>\n            <div id="accountProfile" style="padding:1rem;background:#f7f7f7;margin-bottom:1.5rem;"></div>\n            <div style="display:flex;justify-content:space-between;align-items:center;gap:1rem;margin-bottom:1rem;flex-wrap:wrap;">\n                <h3 style="margin:0;">Order History</h3>\n                <button type="button" class="btn-edit" onclick="loadCustomerOrders()">Refresh</button>\n            </div>\n            <div id="accountOrders" aria-live="polite"><p style="color:#666;">Loading orders…</p></div>\n            <div class="form-actions" style="margin-top:1.5rem;">\n                <button type="button" class="btn-delete" onclick="logoutUser()">Log Out</button>\n                <button type="button" class="btn-cancel" onclick="closeAccountModal()">Close</button>\n            </div>\n        </div>\n    </div>\n\n'''
    if marker not in h: raise SystemExit('auth modal marker')
    h=h.replace(marker,modal+marker,1)

# Give auth dialog semantic state as well.
h=h.replace('<div class="auth-modal" id="authModal">','<div class="auth-modal" id="authModal" role="dialog" aria-modal="true" aria-labelledby="authModalTitle" aria-hidden="true">',1)
h=h.replace("<h2 style=\"font-family: 'Bebas Neue', sans-serif; font-size: 2.5rem; margin-bottom: 1.5rem; letter-spacing: 0.1em; text-align: center;\">Welcome to KEM</h2>","<h2 id=\"authModalTitle\" style=\"font-family: 'Bebas Neue', sans-serif; font-size: 2.5rem; margin-bottom: 1.5rem; letter-spacing: 0.1em; text-align: center;\">Welcome to KEM</h2>",1)
h=h.replace('<input type="text" id="loginIdentifier" placeholder="your@email.com" required>','<input type="email" id="loginIdentifier" placeholder="your@email.com" autocomplete="email" required>',1)
h=h.replace('<a onclick="handleForgotPassword()" style="color: var(--accent); cursor: pointer; font-size: 0.9rem; text-decoration: underline;">Forgot Password?</a>','<button type="button" onclick="handleForgotPassword()" style="border:0;background:none;color:var(--accent);font-size:.9rem;text-decoration:underline;">Forgot Password?</button>',1)

# Insert account functions before auth update button.
account_funcs='''        async function openAccountModal() {\n            if (!auth?.currentUser || !currentUser) { openAuthModal(); return; }\n            const modal=document.getElementById('accountModal');\n            const profile=document.getElementById('accountProfile');\n            profile.innerHTML=`<strong>${escapeHTML(currentUser.name||'Customer')}</strong><div style="color:#666;margin-top:.25rem;">${escapeHTML(currentUser.email||'')}</div>${currentUser.phone?`<div style="color:#666;">${escapeHTML(currentUser.phone)}</div>`:''}`;\n            modal.classList.add('active'); modal.setAttribute('aria-hidden','false'); document.body.style.overflow='hidden';\n            modal.querySelector('.close-modal')?.focus();\n            await loadCustomerOrders();\n        }\n\n        function closeAccountModal() { const modal=document.getElementById('accountModal'); if(!modal)return; modal.classList.remove('active'); modal.setAttribute('aria-hidden','true'); document.body.style.overflow='auto'; }\n\n        async function loadCustomerOrders() {\n            const container=document.getElementById('accountOrders'); if(!container||!cloudFunctions)return; container.innerHTML='<p style="color:#666;">Loading orders…</p>';\n            try {\n                const getCustomerOrders=cloudFunctions.httpsCallable('getCustomerOrders'); const response=await getCustomerOrders(); const customerOrders=Array.isArray(response.data?.orders)?response.data.orders:[];\n                if(!customerOrders.length){container.innerHTML='<div style="padding:2rem;text-align:center;background:#f7f7f7;"><strong>No orders yet</strong><p style="color:#666;margin-top:.5rem;">Your KEM orders will appear here after checkout.</p></div>';return;}\n                container.innerHTML=customerOrders.map(order=>`<article style="border:1px solid var(--border);padding:1rem;margin-bottom:.75rem;"><div style="display:flex;justify-content:space-between;gap:1rem;flex-wrap:wrap;"><strong>${escapeHTML(order.id)}</strong><span class="status-badge status-${escapeHTML(order.status)}">${escapeHTML(order.status)}</span></div><div style="margin-top:.5rem;color:#666;">${escapeHTML(order.createdAt||order.date||'')}</div><div style="margin-top:.5rem;">${Number(order.itemCount||0)} item(s) · <strong>EGP ${Number(order.total||0).toFixed(2)}</strong></div></article>`).join('');\n            } catch(error) { console.error('Unable to load order history:',error); container.innerHTML='<p style="color:var(--accent);">Unable to load your orders. Please try again.</p>'; }\n        }\n\n'''
needle='''                function updateAuthButton() {\n'''
if 'function openAccountModal()' not in h:
    if needle not in h: raise SystemExit('update auth marker')
    h=h.replace(needle,account_funcs+needle,1)

# Auth button becomes account button when logged in.
old="""            if (currentUser) {\n                button.classList.add('logged-in');\n                buttonText.textContent = currentUser.name.split(' ')[0]; // First name only\n            } else {\n                button.classList.remove('logged-in');\n                buttonText.textContent = 'Login';\n            }"""
new="""            if (currentUser) {\n                button.classList.add('logged-in');\n                buttonText.textContent = currentUser.name.split(' ')[0];\n                button.onclick = openAccountModal;\n                button.setAttribute('aria-label', 'Open my account');\n            } else {\n                button.classList.remove('logged-in');\n                buttonText.textContent = 'Login';\n                button.onclick = openAuthModal;\n                button.setAttribute('aria-label', 'Log in or create account');\n            }"""
if old not in h: raise SystemExit('auth update block')
h=h.replace(old,new,1)
h=h.replace("async function logoutUser() {\n            currentUser = null;","async function logoutUser() {\n            closeAccountModal();\n            currentUser = null;",1)

# Add backend own-order callable before createOrder.
backend_marker='''exports.createOrder = onCall(async (request) => {\n'''
if 'exports.getCustomerOrders' not in b:
    code='''exports.getCustomerOrders = onCall(async (request) => {\n  if (!request.auth?.uid) throw new HttpsError('unauthenticated', 'Customer authentication is required.');\n  const uid = request.auth.uid;\n  const snap = await db.ref('orders').once('value');\n  const orders = normalizeList(snap.val()).filter((order) => order?.customerUid === uid).sort((a, z) => String(z.createdAt || z.date || '').localeCompare(String(a.createdAt || a.date || ''))).slice(0, 50).map((order) => ({\n    id: cleanText(order.id, 80),\n    createdAt: order.createdAt || order.date || null,\n    status: cleanText(order.status, 30),\n    total: Math.max(0, normalizeNumber(order.total)),\n    itemCount: normalizeList(order.items).reduce((sum, item) => sum + Math.max(0, Math.floor(normalizeNumber(item.qty))), 0)\n  }));\n  return { orders };\n});\n\n'''
    if backend_marker not in b: raise SystemExit('backend marker')
    b=b.replace(backend_marker,code+backend_marker,1)

p.write_text(h); bp.write_text(b); print('customer account batch applied')
