from pathlib import Path
import re, sys
p=Path(sys.argv[1] if len(sys.argv)>1 else 'index.html');h=p.read_text()
assert 'P2.6 — ACCOUNT / AUTHENTICATION' not in h
CSS='''

        /* P2.6 — ACCOUNT / AUTHENTICATION */
        #authModal.auth-modal,#accountModal.auth-modal{align-items:center;justify-content:center;padding:max(var(--space-24),env(safe-area-inset-top)) var(--page-gutter) max(var(--space-24),env(safe-area-inset-bottom));background:rgba(10,10,10,.76)}
        #authModal .auth-modal-content,#accountModal .auth-modal-content{width:min(100%,560px);max-height:min(880px,calc(100vh - 48px));overflow-y:auto;padding:var(--space-48);border:1px solid var(--color-neutral-200);border-radius:var(--radius-sm);background:var(--color-white);color:var(--color-ink);box-shadow:var(--shadow-panel)}
        #accountModal .auth-modal-content{width:min(100%,960px)}
        .account-kicker,.auth-kicker{margin:0 0 var(--space-8);color:var(--color-neutral-600);font:600 var(--type-metadata)/1.35 var(--font-ui);letter-spacing:.08em;text-transform:uppercase}
        #authModalTitle,#accountModalTitle{margin:0;color:var(--color-ink);font-family:var(--font-display);font-size:var(--type-section-title);font-weight:400;line-height:.95;letter-spacing:.02em}
        .auth-intro,.account-intro{max-width:52ch;margin:var(--space-12) 0 var(--space-24);color:var(--color-neutral-600);font:400 var(--type-ui)/1.55 var(--font-ui)}
        #authModal .close-modal,#accountModal .close-modal{top:var(--space-16);right:var(--space-16)}
        #authModal .auth-tabs{display:grid;grid-template-columns:1fr 1fr;margin:0 0 var(--space-32);border-bottom:1px solid var(--color-neutral-200)}
        #authModal .auth-tab{min-height:48px;padding:var(--space-12) var(--space-16);border:0;border-bottom:2px solid transparent;border-radius:0;background:transparent;color:var(--color-neutral-600);font:600 var(--type-ui)/1.2 var(--font-ui)}
        #authModal .auth-tab.active{border-bottom-color:var(--color-ink);color:var(--color-ink)}
        #authModal .auth-form{display:none}#authModal .auth-form.active{display:block}
        #authModal .auth-input-group{margin-bottom:20px}#authModal .auth-input-group label{display:block;margin-bottom:var(--space-8);color:var(--color-ink);font:600 var(--type-ui)/1.35 var(--font-ui)}
        #authModal .auth-input-group input,#authModal .auth-reset-panel input{width:100%;min-width:0;min-height:48px;padding:var(--space-12) var(--space-16);border:1px solid var(--color-neutral-200);border-radius:var(--radius-xs);background:var(--color-white);color:var(--color-ink);font:400 var(--type-ui)/1.4 var(--font-ui)}
        #authModal .auth-submit,#authModal .auth-reset-submit{width:100%;min-height:52px;padding:var(--space-16) var(--space-24);border:1px solid var(--color-ink);border-radius:var(--radius-xs);background:var(--color-ink);color:var(--color-white);font:600 var(--type-ui)/1.2 var(--font-ui);letter-spacing:.04em;text-transform:uppercase}
        #authModal .auth-submit:hover,#authModal .auth-reset-submit:hover{border-color:var(--color-kem-pink);background:var(--color-kem-pink)}
        .auth-secondary-action,.auth-switch button,.auth-reset-back{min-height:44px;padding:var(--space-8) 0;border:0;background:transparent;color:var(--color-ink);font:600 var(--type-ui)/1.25 var(--font-ui);text-decoration:underline;text-underline-offset:3px}
        .auth-forgot{display:flex;justify-content:flex-end;margin:calc(-1 * var(--space-8)) 0 var(--space-16)}.auth-switch{margin-top:var(--space-16);color:var(--color-neutral-600);text-align:center;font:400 var(--type-ui)/1.45 var(--font-ui)}.auth-switch button{margin-left:var(--space-4)}
        #authModal .auth-divider{display:flex;align-items:center;gap:var(--space-12);margin:var(--space-24) 0;color:var(--color-neutral-400);font:600 var(--type-metadata)/1 var(--font-ui);letter-spacing:.08em}#authModal .auth-divider:before,#authModal .auth-divider:after{content:'';flex:1;height:1px;background:var(--color-neutral-200)}
        #authFeedback{margin:0 0 20px}#authFeedback:empty{display:none}#authFeedback[class]{padding:var(--space-12) var(--space-16)}#authFeedback.auth-feedback-error{color:var(--color-error);background:var(--color-error-surface);border:1px solid #F3B8B3}#authFeedback.auth-feedback-success{color:var(--color-success);background:var(--color-success-surface);border:1px solid #B8DEC9}#authFeedback.auth-feedback-info{color:var(--color-info);background:var(--color-info-surface);border:1px solid #BCD0FA}
        .auth-reset-panel[hidden]{display:none}.auth-reset-panel h3{margin:0 0 var(--space-8);font-family:var(--font-display);font-size:var(--type-product-title);font-weight:400}.auth-reset-panel p{margin:0 0 20px;color:var(--color-neutral-600);font:400 var(--type-ui)/1.55 var(--font-ui)}.auth-reset-actions{display:grid;gap:var(--space-12)}
        .account-layout{display:grid;grid-template-columns:minmax(0,.8fr) minmax(0,1.2fr);gap:var(--space-48);align-items:start}.account-section{min-width:0;padding-top:var(--space-24);border-top:1px solid var(--color-neutral-200)}.account-section+.account-section{margin-top:var(--space-32)}.account-section-header{display:flex;align-items:center;justify-content:space-between;gap:var(--space-16);margin-bottom:var(--space-16)}.account-section h3{margin:0;font-family:var(--font-display);font-size:var(--type-product-title);font-weight:400;line-height:1}
        .account-refresh,.account-close,.account-logout{min-height:44px;padding:var(--space-12) var(--space-16);border-radius:var(--radius-xs);font:600 var(--type-ui)/1.2 var(--font-ui)}.account-refresh,.account-close{border:1px solid var(--color-neutral-200);background:var(--color-white);color:var(--color-ink)}.account-logout{border:1px solid var(--color-ink);background:var(--color-ink);color:var(--color-white)}.account-logout:hover{border-color:var(--color-kem-pink);background:var(--color-kem-pink)}
        #accountProfile{padding:0;background:transparent}.account-profile-name{margin:0 0 var(--space-8);font:600 var(--type-product-title)/1.15 var(--font-ui);overflow-wrap:anywhere}.account-profile-meta{margin:var(--space-4) 0 0;color:var(--color-neutral-600);font:400 var(--type-ui)/1.5 var(--font-ui);overflow-wrap:anywhere}
        #accountAddresses,#accountOrders{display:grid;gap:var(--space-12)}.account-address{padding:var(--space-16);border:1px solid var(--color-neutral-200);background:var(--color-neutral-50)}.account-address-head{display:flex;align-items:center;justify-content:space-between;gap:var(--space-12);margin-bottom:var(--space-8)}.account-address-label{font:600 var(--type-ui)/1.3 var(--font-ui)}.account-address-default{color:var(--color-success);font:600 var(--type-metadata)/1.2 var(--font-ui);text-transform:uppercase;letter-spacing:.05em}.account-address-copy{color:var(--color-neutral-600);font:400 var(--type-ui)/1.5 var(--font-ui);overflow-wrap:anywhere}
        .account-order{padding:var(--space-16) 0;border-bottom:1px solid var(--color-neutral-200)}.account-order:first-child{padding-top:0}.account-order-head{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--space-16)}.account-order-id{color:var(--color-ink);font:600 var(--type-ui)/1.35 var(--font-ui);overflow-wrap:anywhere}.account-order-date{margin-top:var(--space-4);color:var(--color-neutral-600);font:400 var(--type-metadata)/1.4 var(--font-ui);overflow-wrap:anywhere}.account-order-meta{display:flex;flex-wrap:wrap;justify-content:space-between;gap:var(--space-12);margin-top:var(--space-12);color:var(--color-neutral-600);font:400 var(--type-ui)/1.4 var(--font-ui)}.account-order-total{color:var(--color-ink);font-weight:600}
        .account-empty,.account-loading,.account-error{padding:var(--space-24);border:1px solid var(--color-neutral-200);background:var(--color-neutral-50)}.account-error{border-color:#F3B8B3;background:var(--color-error-surface);color:var(--color-error)}.account-actions{display:flex;justify-content:flex-end;gap:var(--space-12);margin-top:var(--space-32);padding-top:var(--space-24);border-top:1px solid var(--color-neutral-200)}
        #authModal :is(button,input):focus-visible,#accountModal :is(button,input):focus-visible{outline:3px solid var(--color-kem-pink);outline-offset:3px}
        @media(max-width:767px){#authModal.auth-modal,#accountModal.auth-modal{align-items:flex-start;padding:var(--space-16) var(--page-gutter)}#authModal .auth-modal-content,#accountModal .auth-modal-content{max-height:calc(100vh - 32px);padding:var(--space-32) var(--space-24)}.account-layout{grid-template-columns:1fr;gap:var(--space-32)}.account-actions{flex-direction:column-reverse}.account-actions button{width:100%}}
        @media(max-width:420px){#authModal .auth-modal-content,#accountModal .auth-modal-content{padding:var(--space-32) var(--space-16) var(--space-24)}.account-section-header{align-items:flex-start}.account-order-head{display:grid;grid-template-columns:1fr}.account-order-head .status-badge{justify-self:start}}
        @media(prefers-reduced-motion:reduce){#authModal *,#accountModal *{transition-duration:.01ms!important;animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important}}
'''
h=h.replace('\n    </style>',CSS+'\n    </style>',1)
ACCOUNT='''    <!-- Customer Account Modal -->
    <div class="auth-modal" id="accountModal" role="dialog" aria-modal="true" aria-labelledby="accountModalTitle" aria-describedby="accountModalIntro" aria-hidden="true"><div class="auth-modal-content"><button type="button" class="close-modal" onclick="closeAccountModal()" aria-label="Close account">×</button><header><p class="account-kicker">KEM / Account</p><h2 id="accountModalTitle">My Account</h2><p class="account-intro" id="accountModalIntro">Your KEM profile, saved addresses and order history.</p></header><div class="account-layout"><div><section class="account-section" aria-labelledby="accountProfileTitle"><div class="account-section-header"><h3 id="accountProfileTitle">Profile</h3></div><div id="accountProfile"></div></section><section class="account-section" aria-labelledby="accountAddressesTitle"><div class="account-section-header"><h3 id="accountAddressesTitle">Saved Addresses</h3></div><div id="accountAddresses" aria-live="polite"></div></section></div><section class="account-section" aria-labelledby="accountOrdersTitle"><div class="account-section-header"><h3 id="accountOrdersTitle">Orders</h3><button type="button" class="account-refresh" onclick="loadCustomerOrders()">Refresh</button></div><div id="accountOrders" aria-live="polite" aria-busy="true"><div class="account-loading">Loading orders…</div></div></section></div><div class="account-actions"><button type="button" class="account-close" onclick="closeAccountModal()">Close</button><button type="button" class="account-logout" onclick="logoutUser()">Log Out</button></div></div></div>'''
h,n=re.subn(r'    <!-- Customer Account Modal -->.*?(?=\n\n    <!-- Auth Modal -->)',ACCOUNT,h,count=1,flags=re.S);assert n==1
AUTH='''    <!-- Auth Modal -->
    <div class="auth-modal" id="authModal" role="dialog" aria-modal="true" aria-labelledby="authModalTitle" aria-describedby="authModalIntro" aria-hidden="true"><div class="auth-modal-content"><button type="button" class="close-modal" onclick="closeAuthModal()" aria-label="Close account sign in">×</button><header><p class="auth-kicker">KEM / Account</p><h2 id="authModalTitle">Account</h2><p class="auth-intro" id="authModalIntro">Sign in to view your KEM account, saved addresses and orders.</p></header><div id="authFeedback" role="status" aria-live="polite"></div><div class="auth-tabs" role="tablist" aria-label="Account access"><button type="button" class="auth-tab active" id="loginTab" role="tab" aria-selected="true" aria-controls="loginForm" onclick="switchAuthTab('login')">Login</button><button type="button" class="auth-tab" id="signupTab" role="tab" aria-selected="false" aria-controls="signupForm" onclick="switchAuthTab('signup')">Sign Up</button></div>
    <form class="auth-form active" id="loginForm" role="tabpanel" aria-labelledby="loginTab" onsubmit="handleLogin(event)"><div class="auth-input-group"><label for="loginIdentifier">Email</label><input type="email" id="loginIdentifier" placeholder="your@email.com" autocomplete="email" required></div><div class="auth-input-group"><label for="loginPassword">Password</label><input type="password" id="loginPassword" placeholder="Enter your password" autocomplete="current-password" required></div><div class="auth-forgot"><button type="button" class="auth-secondary-action" onclick="handleForgotPassword()">Forgot Password?</button></div><button type="submit" class="auth-submit">Login</button><div class="auth-divider" aria-hidden="true">OR</div><div id="googleSignInButtonLogin"><div style="text-align:center;padding:1rem;background:#f5f5f5;border:1px solid #ddd;color:#666;">Loading Google Sign-In...</div></div><div class="auth-switch">Don't have an account?<button type="button" onclick="switchAuthTab('signup')">Sign Up</button></div></form>
    <form class="auth-form" id="signupForm" role="tabpanel" aria-labelledby="signupTab" onsubmit="handleSignup(event)"><div class="auth-input-group"><label for="signupName">Full Name *</label><input type="text" id="signupName" placeholder="Your name" autocomplete="name" required></div><div class="auth-input-group"><label for="signupEmail">Email *</label><input type="email" id="signupEmail" placeholder="your@email.com" autocomplete="email" required></div><div class="auth-input-group"><label for="signupPhone">Phone Number</label><input type="tel" id="signupPhone" placeholder="+20123456789" autocomplete="tel"></div><div class="auth-input-group"><label for="signupPassword">Password *</label><input type="password" id="signupPassword" placeholder="Create a password" autocomplete="new-password" minlength="6" required></div><button type="submit" class="auth-submit">Create Account</button><div class="auth-divider" aria-hidden="true">OR</div><div id="googleSignInButtonSignup"><div style="text-align:center;padding:1rem;background:#f5f5f5;border:1px solid #ddd;color:#666;">Loading Google Sign-In...</div></div><div class="auth-switch">Already have an account?<button type="button" onclick="switchAuthTab('login')">Login</button></div></form>
    <section class="auth-reset-panel" id="resetPasswordPanel" aria-labelledby="resetPasswordTitle" hidden><h3 id="resetPasswordTitle">Reset Password</h3><p>Enter the email address for your KEM account. The existing password-reset service will send the reset email.</p><form id="resetPasswordForm" onsubmit="handlePasswordResetSubmit(event)"><div class="auth-input-group"><label for="resetEmail">Email</label><input type="email" id="resetEmail" autocomplete="email" required></div><div class="auth-reset-actions"><button type="submit" class="auth-reset-submit">Send Reset Email</button><button type="button" class="auth-reset-back" onclick="switchAuthTab('login')">Return to Login</button></div></form></section></div></div>'''
h,n=re.subn(r'    <!-- Auth Modal -->.*?(?=\n\n    <!-- Google Sign-In Modal -->)',AUTH,h,count=1,flags=re.S);assert n==1
GLOBAL='''        // Auth Modal Functions (Global)
        let authDialogReturnFocus=null,accountDialogReturnFocus=null;
        function setAuthFeedback(message='',state='info'){const f=document.getElementById('authFeedback');if(!f)return;f.textContent=message;f.className=message?`auth-feedback-${state}`:'';f.setAttribute('role',state==='error'?'alert':'status')}
        window.openAuthModal=function(){const m=document.getElementById('authModal');if(!m)return;authDialogReturnFocus=document.activeElement&&!m.contains(document.activeElement)?document.activeElement:authDialogReturnFocus;m.classList.add('active');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';switchAuthTab('login');requestAnimationFrame(()=>document.getElementById('loginIdentifier')?.focus());if(window.googleLibraryLoaded&&typeof window.initializeGoogleSignIn==='function')setTimeout(()=>window.initializeGoogleSignIn(),100)}
        window.closeAuthModal=function(){const m=document.getElementById('authModal');if(!m)return;m.classList.remove('active');m.setAttribute('aria-hidden','true');document.body.style.overflow='auto';setAuthFeedback('');const t=authDialogReturnFocus;authDialogReturnFocus=null;if(t?.isConnected)requestAnimationFrame(()=>t.focus())}
        window.switchAuthTab=function(tab){const login=tab==='login';document.getElementById('loginForm')?.classList.toggle('active',login);document.getElementById('signupForm')?.classList.toggle('active',!login);const r=document.getElementById('resetPasswordPanel');if(r)r.hidden=true;const l=document.getElementById('loginTab'),s=document.getElementById('signupTab');l?.classList.toggle('active',login);s?.classList.toggle('active',!login);l?.setAttribute('aria-selected',String(login));s?.setAttribute('aria-selected',String(!login));setAuthFeedback('')}
        function showPasswordReset(){document.getElementById('loginForm')?.classList.remove('active');document.getElementById('signupForm')?.classList.remove('active');const r=document.getElementById('resetPasswordPanel');if(r)r.hidden=false;const e=document.getElementById('loginIdentifier')?.value.trim(),i=document.getElementById('resetEmail');if(i&&e)i.value=e;setAuthFeedback('');requestAnimationFrame(()=>i?.focus())}'''
h,n=re.subn(r'        // Auth Modal Functions \(Global\).*?(?=\n        // Custom Cursor)',GLOBAL,h,count=1,flags=re.S);assert n==1
h,n=re.subn(r'\n        function switchAuthTab\(tab\) \{.*?\n        \}\n\n(?=        async function handleLogin)', '\n', h,count=1,flags=re.S);assert n==1
h=h.replace("            try {\n                const credential = await auth.signInWithEmailAndPassword(email, password);","            setAuthFeedback('Signing in…','info');\n            try {\n                const credential = await auth.signInWithEmailAndPassword(email, password);",1)
h=h.replace("console.error('Login failed:', error);\n                alert('Unable to sign in with those credentials.');","console.error('Login failed:', error);\n                setAuthFeedback('Unable to sign in with those credentials.','error');\n                alert('Unable to sign in with those credentials.');",1)
h=h.replace("            try {\n                const credential = await auth.createUserWithEmailAndPassword(email, password);","            setAuthFeedback('Creating your account…','info');\n            try {\n                const credential = await auth.createUserWithEmailAndPassword(email, password);",1)
h=h.replace("console.error('Signup failed:', error);\n                alert(error?.message || 'Unable to create your account.');","console.error('Signup failed:', error);\n                setAuthFeedback('Unable to create your account. Please check the details and try again.','error');\n                alert(error?.message || 'Unable to create your account.');",1)
RESET='''                function handleForgotPassword(){showPasswordReset()}
        async function handlePasswordResetSubmit(event){event.preventDefault();const email=document.getElementById('resetEmail').value.trim().toLowerCase();if(!email)return;setAuthFeedback('Sending password reset email…','info');try{await auth.sendPasswordResetEmail(email);setAuthFeedback('If the account exists, a password reset email has been sent.','success')}catch(error){console.error('Password reset failed:',error);setAuthFeedback('Unable to start password reset. Please check the address and try again.','error')}}'''
h,n=re.subn(r"                async function handleForgotPassword\(\) \{.*?\n        \}",RESET,h,count=1,flags=re.S);assert n==1
ACCOUNTJS='''        function renderAccountAddresses(){const c=document.getElementById('accountAddresses');if(!c)return;const u=currentUser?.uid?users[currentUser.uid]:null,a=Array.isArray(u?.savedAddresses)?u.savedAddresses:(Array.isArray(currentUser?.savedAddresses)?currentUser.savedAddresses:[]);if(!a.length){c.innerHTML='<div class="account-empty"><strong>No saved addresses</strong><p class="account-profile-meta">Saved addresses will appear here when available on your account.</p></div>';return}c.innerHTML=a.map(x=>`<article class="account-address"><div class="account-address-head"><span class="account-address-label">${escapeHTML(x.label||'Saved address')}</span>${x.isDefault?'<span class="account-address-default">Default</span>':''}</div><div class="account-address-copy">${escapeHTML(x.address||'')}${x.houseNumber?`<br>Building: ${escapeHTML(x.houseNumber)}`:''}${x.floor?`, Floor: ${escapeHTML(x.floor)}`:''}${x.city?`<br>${escapeHTML(x.city)}`:''}${x.postal?` · ${escapeHTML(x.postal)}`:''}</div></article>`).join('')}
        async function openAccountModal(){if(!auth?.currentUser||!currentUser){openAuthModal();return}const m=document.getElementById('accountModal'),profile=document.getElementById('accountProfile');accountDialogReturnFocus=document.activeElement&&!m.contains(document.activeElement)?document.activeElement:accountDialogReturnFocus;profile.innerHTML=`<p class="account-profile-name">${escapeHTML(currentUser.name||'Customer')}</p><p class="account-profile-meta">${escapeHTML(currentUser.email||'')}</p>${currentUser.phone?`<p class="account-profile-meta">${escapeHTML(currentUser.phone)}</p>`:''}`;renderAccountAddresses();m.classList.add('active');m.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';requestAnimationFrame(()=>m.querySelector('.close-modal')?.focus());await loadCustomerOrders()}
        function closeAccountModal(){const m=document.getElementById('accountModal');if(!m)return;m.classList.remove('active');m.setAttribute('aria-hidden','true');document.body.style.overflow='auto';const t=accountDialogReturnFocus;accountDialogReturnFocus=null;if(t?.isConnected)requestAnimationFrame(()=>t.focus())}
        async function loadCustomerOrders(){const c=document.getElementById('accountOrders');if(!c||!cloudFunctions)return;c.setAttribute('aria-busy','true');c.innerHTML='<div class="account-loading">Loading orders…</div>';try{const f=cloudFunctions.httpsCallable('getCustomerOrders'),r=await f(),o=Array.isArray(r.data?.orders)?r.data.orders:[];if(!o.length){c.innerHTML='<div class="account-empty"><strong>No orders yet</strong><p class="account-profile-meta">Your KEM orders will appear here after checkout.</p></div>';return}c.innerHTML=o.map(x=>`<article class="account-order"><div class="account-order-head"><div><div class="account-order-id">${escapeHTML(x.id)}</div><div class="account-order-date">${escapeHTML(x.createdAt||x.date||'')}</div></div><span class="status-badge status-${escapeHTML(x.status)}">${escapeHTML(x.status)}</span></div><div class="account-order-meta"><span>${Number(x.itemCount||0)} item(s)</span><span class="account-order-total">EGP ${Number(x.total||0).toFixed(2)}</span></div></article>`).join('')}catch(error){console.error('Unable to load order history:',error);c.innerHTML='<div class="account-error" role="alert">Unable to load your orders. Please try again.</div>'}finally{c.setAttribute('aria-busy','false')}}'''
h,n=re.subn(r'        async function openAccountModal\(\) \{.*?\n        \}\n\n(?=                function updateAuthButton)',ACCOUNTJS+'\n\n',h,count=1,flags=re.S);assert n==1
for x in ["auth.signInWithEmailAndPassword(email, password)","auth.createUserWithEmailAndPassword(email, password)",'credential.user.sendEmailVerification()',"auth.sendPasswordResetEmail(email)","cloudFunctions.httpsCallable('getCustomerOrders')",'async function logoutEmployee()','P2.5 — CART / CHECKOUT','P2.4 — PRODUCT DETAIL','P2.3 — COLLECTION / SHOP','P2.2 — HOMEPAGE','P2.1 — HEADER / NAVIGATION']:assert x in h,x
assert "prompt('Enter your email address to reset your password:')" not in h
p.write_text(h);print('Applied P2.6')
